language: python

python:
     - "2.7"

env:
    matrix:
        - TARGETS="devo8 devo10" MAKETARGET="html pdf"

# use new docker environment
sudo: false

install:
    - pip install virtualenv

addons:
  apt:
    packages:
        - build-essential
        - inkscape

script:
    - for i in $TARGETS; do \
          which make
          echo "make TARGET=$i $MAKETARGET"; \
          make TARGET=$i $MAKETARGET; \
      done
