language: python

python:
     - "2.7"

env:
    matrix:
        - TARGETS="devo8 devo10" MAKETARGET="html pdf"

# use new docker environment
sudo: false

addons:
  apt:
    packages:
        #- build-essential
        - inkscape
        

script:
    - which make
    - echo "make TARGET='$TARGETS' $MAKETARGET"
    - for i in $TARGETS; do \
          which make
          echo "make TARGET=$i $MAKETARGET"; \
          make TARGET=$i $MAKETARGET; \
      done
